// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnowrunnerMerger.Api.Data;

#nullable disable

namespace SnowrunnerMerger.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117095022_AddMapsTable")]
    partial class AddMapsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapStoredSaveInfo", b =>
                {
                    b.Property<string>("DiscoveredMapsId")
                        .HasColumnType("text");

                    b.Property<Guid>("StoredSaveInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("DiscoveredMapsId", "StoredSaveInfoId");

                    b.HasIndex("StoredSaveInfoId");

                    b.ToTable("MapStoredSaveInfo");
                });

            modelBuilder.Entity("SaveGroupUser", b =>
                {
                    b.Property<Guid>("JoinedGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("uuid");

                    b.HasKey("JoinedGroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("SaveGroupUser");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.OAuth.OAuthConnection", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Provider", "ProviderAccountId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("OAuthConnections");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("UserTokens");

                    b.HasDiscriminator<string>("TokenType").HasValue("UserToken");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasLongLivedRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.Map", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = "US_01",
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = "US_02",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = "US_03",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = "US_04",
                            Name = "Yukon"
                        },
                        new
                        {
                            Id = "US_06",
                            Name = "Maine"
                        },
                        new
                        {
                            Id = "US_07",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = "US_09",
                            Name = "Ontario"
                        },
                        new
                        {
                            Id = "US_10",
                            Name = "British Columbia"
                        },
                        new
                        {
                            Id = "US_11",
                            Name = "Scandinavia"
                        },
                        new
                        {
                            Id = "US_12",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = "US_14",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = "US_15",
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = "US_16",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = "RU_02",
                            Name = "Taymyr"
                        },
                        new
                        {
                            Id = "RU_03",
                            Name = "Kola Peninsula"
                        },
                        new
                        {
                            Id = "RU_04",
                            Name = "Amur"
                        },
                        new
                        {
                            Id = "RU_05",
                            Name = "Don"
                        },
                        new
                        {
                            Id = "RU_08",
                            Name = "Belozersk Glades"
                        },
                        new
                        {
                            Id = "RU_13",
                            Name = "Almaty Region"
                        });
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.SaveGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("SaveGroups");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.StoredSaveInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SaveGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaveNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SaveGroupId");

                    b.ToTable("StoredSaves");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.AccountCompletionToken", b =>
                {
                    b.HasBaseType("SnowrunnerMerger.Api.Models.Auth.Tokens.UserToken");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UserTokens", t =>
                        {
                            t.Property("Provider")
                                .HasColumnName("AccountCompletionToken_Provider");

                            t.Property("ProviderAccountId")
                                .HasColumnName("AccountCompletionToken_ProviderAccountId");
                        });

                    b.HasDiscriminator().HasValue("AccountCompletion");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.AccountConfirmationToken", b =>
                {
                    b.HasBaseType("SnowrunnerMerger.Api.Models.Auth.Tokens.UserToken");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("AccountConfirmationToken_UserId");
                        });

                    b.HasDiscriminator().HasValue("AccountConfirmation");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.AccountLinkingToken", b =>
                {
                    b.HasBaseType("SnowrunnerMerger.Api.Models.Auth.Tokens.UserToken");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("AccountLinkingToken_UserId");
                        });

                    b.HasDiscriminator().HasValue("AccountLinking");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.PasswordResetToken", b =>
                {
                    b.HasBaseType("SnowrunnerMerger.Api.Models.Auth.Tokens.UserToken");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("PasswordReset");
                });

            modelBuilder.Entity("MapStoredSaveInfo", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Saves.Map", null)
                        .WithMany()
                        .HasForeignKey("DiscoveredMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowrunnerMerger.Api.Models.Saves.StoredSaveInfo", null)
                        .WithMany()
                        .HasForeignKey("StoredSaveInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaveGroupUser", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Saves.SaveGroup", null)
                        .WithMany()
                        .HasForeignKey("JoinedGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.OAuth.OAuthConnection", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.UserSession", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.SaveGroup", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.StoredSaveInfo", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Saves.SaveGroup", "SaveGroup")
                        .WithMany("StoredSaves")
                        .HasForeignKey("SaveGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveGroup");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.AccountConfirmationToken", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.AccountLinkingToken", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.Tokens.PasswordResetToken", b =>
                {
                    b.HasOne("SnowrunnerMerger.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Auth.User", b =>
                {
                    b.Navigation("OwnedGroups");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("SnowrunnerMerger.Api.Models.Saves.SaveGroup", b =>
                {
                    b.Navigation("StoredSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
